GET http://localhost:3000/

###
GET http://localhost:3000/libros

###
GET http://localhost:3000/cualquiercosa

###
POST http://localhost:3000/eco
Content-Type: application/json

{
  "titulo": "Libro de prueba",
  "autor": "Yo"
}
###
POST http://localhost:3000/eco
Content-Type: application/json

hola