### 1. Listar todos los libros
GET http://localhost:3000/books

### 2. Filtrar por autor
GET http://localhost:3000/books?author=Orwell

### 3a. Buscar libro existente (debe dar 200)
GET http://localhost:3000/books/1

### 3b. Buscar libro inexistente (debe dar 404)
GET http://localhost:3000/books/999

### 4a. Crear libro válido (debe dar 201)
POST http://localhost:3000/books
Content-Type: application/json

{
  "isbn": "9788437604947",
  "title": "Rayuela",
  "author": "Julio Cortázar",
  "stock": 4
}

### 4b. Crear libro sin título (debe dar 400)
POST http://localhost:3000/books
Content-Type: application/json

{
  "author": "Anónimo"
}

### 5a. Actualizar libro 1
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "isbn": "9780307474728",
  "title": "Cien años de soledad (edición especial)",
  "author": "Gabriel García Márquez",
  "stock": 10
}

### 5b. Actualizar libro inexistente (debe dar 404)
PUT http://localhost:3000/books/999
Content-Type: application/json

{
  "title": "No existe",
  "author": "Nadie"
}

### 6a. Borrar libro 2
DELETE http://localhost:3000/books/2

### 6b. Borrar libro inexistente (debe dar 404)
DELETE http://localhost:3000/books/999

### 7. PATCH para actualizar stock de libro 1
PATCH http://localhost:3000/books/1
Content-Type: application/json

{
  "stock": 15
}

### 8. Ver cómo quedó la lista
GET http://localhost:3000/books

### 9. Prueba GET con Sort title
GET http://localhost:3000/books?sort=title

### 10. Prueba GET con Sort stock
GET http://localhost:3000/books?sort=stock

### 11. Prueba GET con Sort -stock
GET http://localhost:3000/books?sort=-stock

### 12. Prueba GET Página 1, de a 2
GET http://localhost:3000/books?page=1&limit=2

### 13. Prueba GET Página 2, de a 2
GET http://localhost:3000/books?page=2&limit=2

### 14. Prueba GET Página 3, de a 2
GET http://localhost:3000/books?page=3&limit=2

### 15. Prueba GET con Sort y Paginación
GET http://localhost:3000/books?sort=-stock&limit=3

### 16. Ruta inexistente (debe dar 404 estandarizado)
GET http://localhost:3000/cualquier-cosa

### 17. Listar autores
GET http://localhost:3000/authors

### 18. Buscar autor existente (debe dar 200)
GET http://localhost:3000/authors/1

### 19. Buscar autor inexistente (debe dar 404)
GET http://localhost:3000/authors/999
